baseURL = "http://example.org"
title = "IB Authors"
theme = "zzo"


defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

summaryLength = 70
buildFuture = true

copyright = "&copy;{year}, All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100

enableGitInfo = false
googleAnalytics = ""

[permalinks]
  posts = "/tutorial/:slug/"
  articles = "/articles/:slug/"
  bits = "/bits/:slug/"
  snippets = "/snippets/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  
  article_tag="article_tags"
  article_category = "article_categories"
  bits_tag="bits_tags"
  bits_category = "bits_categories"
  snippet_tag="snippet_tags"
  snippet_category = "snippet_categories"



